export const shoppingCart = [
  { productName: "米蓓尔粉水", price: 268, categoryCouponType: "life", categoryCouponId: 1, moneyOffId: 0, isMoneyOff: true, productCoupon: 28, deposit: 30 },
  { productName: "purid2号精华", price: 321.3, categoryCouponType: "life", isMoneyOff: true, productCoupon: 0, deposit: 60 },
  { productName: "理肤泉B5面膜", price: 320, categoryCouponType: "life", isMoneyOff: true, productCoupon: 12, deposit: 50 },
  { productName: "花西子眉笔", price: 79, categoryCouponType: "makeup", isMoneyOff: true, productCoupon: 0, deposit: 10 },
  { productName: "花西子散粉", price: 149, categoryCouponType: "makeup", isMoneyOff: true, productCoupon: 20, deposit: 20 },
  { productName: "珀莱雅红宝石面霜", price: 339, categoryCouponType: "makeup", isMoneyOff: true, productCoupon: 10, deposit: 40 },
  { productName: "珀莱雅双抗面膜", price: 496, categoryCouponType: "makeup", isMoneyOff: true, productCoupon: 50, deposit: 50 },
  { productName: "伊肤泉喷雾", price: 99, categoryCouponType: "makeup", isMoneyOff: true, productCoupon: 30, deposit: 10 },
  { productName: "薇诺娜冻干面膜", price: 657, categoryCouponType: "makeup", isMoneyOff: true, productCoupon: 258, deposit: 70 },
  { productName: "优时颜眼霜", price: 320, categoryCouponType: "makeup", isMoneyOff: true, productCoupon: 0, deposit: 40 },
  { productName: "素肌良品保暖内衣", price: 618, categoryCouponType: "", isMoneyOff: true, productCoupon: 260, deposit: 80 },
  { productName: "蕉内内裤", price: 198, categoryCouponType: "", isMoneyOff: true, productCoupon: 49, deposit: 20 },
  { productName: "蕉内热皮", price: 466, categoryCouponType: "", isMoneyOff: true, productCoupon: 148, deposit: 60 },
  { productName: "摩飞暖菜板", price: 449, categoryCouponType: "", isMoneyOff: true, productCoupon: 70, deposit: 50 },
  { productName: "seesaw囤货装", price: 318, categoryCouponType: "", isMoneyOff: true, productCoupon: 43, deposit: 40 },
  { productName: "三顿半80颗", price: 609, categoryCouponType: "", isMoneyOff: true, productCoupon: 110, deposit: 50 },
  { productName: "三顿半60颗", price: 309, categoryCouponType: "", isMoneyOff: true, productCoupon: 0, cutPrice: 50, deposit: 40 },
  { productName: "boscia洁面", price: 202, categoryCouponType: "", isMoneyOff: true, productCoupon: 34, deposit: 30 },
  { productName: "addicition防晒", price: 322, categoryCouponType: "", isMoneyOff: true, productCoupon: 4, deposit: 40 },
  { productName: "馥郁满铺水", price: 698, categoryCouponType: "", isMoneyOff: true, productCoupon: 260, deposit: 80 },
  { productName: "科瑞肤面霜", price: 420, categoryCouponType: "", isMoneyOff: true, productCoupon: 25, deposit: 50 },
  { productName: "科瑞肤抗老精华", price: 500, categoryCouponType: "", isMoneyOff: true, productCoupon: 20, deposit: 50 },
  { productName: "OOAK项链", price: 1200, categoryCouponType: "", isMoneyOff: true, productCoupon: 651, deposit: 100 }

];
